# Generated by Django 2.0.1 on 2018-03-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('itemstock', models.PositiveIntegerField()),
                ('itemcost', models.PositiveIntegerField()),
            ],
        ),
    ]
