# Generated by Django 2.0.1 on 2018-03-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='billdetails',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('billnumber', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
