# Generated by Django 2.0.1 on 2018-03-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cas', '0002_billdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetails',
            name='billdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
