# Generated by Django 2.0.1 on 2018-03-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cas', '0003_billdetails_billdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetails',
            name='billdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
