# Generated by Django 2.0.1 on 2018-03-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cas', '0004_auto_20180322_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billnumber', models.PositiveIntegerField()),
                ('itemname', models.CharField(max_length=100)),
            ],
        ),
    ]
